platform: Any CPU
configuration: Release

build:
  parallel: true
  project: Source/Apskaita5/Apskaita5.sln

before_build:
  - nuget restore Source/Apskaita5/Apskaita5.sln

after_build:
  - rd /q /s de es fr it ja ko pt ru zh-CHS zh-CHT app.publish
  - del /q Microsoft.VisualStudio.*
  - del /q *.xml

artifacts:
  - path: Source\Apskaita5\Apskaita3\Apskaita\bin\Release
    name: Apskaita5